/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AeriaButton: typeof import('@aeria-ui/ui')['AeriaButton']
    AeriaForm: typeof import('@aeria-ui/ui')['AeriaForm']
    AeriaInput: typeof import('@aeria-ui/ui')['AeriaInput']
    AeriaSelect: typeof import('@aeria-ui/ui')['AeriaSelect']
    ComponentA: typeof import('./../src/components/component-a.vue')['default']
    ComponentB: typeof import('./../src/components/component-b.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
