#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

for ws in $(git diff --name-only --cached | grep -oE 'packages/([^/]+)' | uniq); do
  pnpm --filter="./${ws}" lint:fix
done

if $(git diff --name-only --cached | grep -q '^pnpm-lock.yaml$'); then
  git add pnpm-lock.yaml
  git commit -m 'chore: update lockfile'
fi

git rm -f --ignore-unmatch packages/packages
